# Generated by Django 5.2 on 2025-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artist_options_event_artist_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
