# Generated by Django 5.2 on 2025-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_artists_event_artist_event_featured_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Performer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(related_name='events', to='core.performer'),
        ),
    ]
