# Generated by Django 5.2 on 2025-04-11 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_artist_performance_performer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='day',
        ),
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 11, 17, 49, 38, 329623)),
            preserve_default=False,
        ),
    ]
