# Generated by Django 5.2 on 2025-04-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_performance_options_remove_performance_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='image',
            field=models.ImageField(blank=True, upload_to='artists/'),
        ),
    ]
