# Generated by Django 5.2 on 2025-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_hero_image_alter_performer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='image',
            field=models.ImageField(upload_to='artists/'),
        ),
    ]
