# Generated by Django 5.2 on 2025-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_hero_image_alter_performer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
