# Generated by Django 5.2 on 2025-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_event_name_alter_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
